### ISSUE TITLE
只能依赖环境变量，不支持外部传入参数启动么

### ISSUE THREAD

**Issue by elegance** [zhenghan008/redisKeyMetrics#1]
有以下几个疑问
1. 只能依赖环境变量，不支持外部传入参数启动么，比如地址、密码.  配置错误未指定时卡住，console没有错误日志输出
2. 端口也是固定的9022
3. sampleType 是否同时支持big,hot,mem

**Comment by zhenghan008** [comment]
这几个问题之前是有考虑过的，只是之前开发这个主要是自用的，也比较急，就先能用就行，你说的这几个功能我有计划迭代掉，等我这两天开发测试没啥问题就发布了。前两个问题比较好解决，最后一个其实也有方案解决，主要是怕同时扫描三个在redis负载比较高的情况下可能会造成麻烦，我先想想看，可能会做成一个参数开关自己选择并发执行还是串行吧。

**Comment by zhenghan008** [comment]
> 有以下几个疑问
> 
> 1. 只能依赖环境变量，不支持外部传入参数启动么，比如地址、密码.  配置错误未指定时卡住，console没有错误日志输出
> 2. 端口也是固定的9022
> 3. sampleType 是否同时支持big,hot,mem

程序已更新，目前测试单机的情况是没问题的。集群的情况我还要再测试看看。

**Comment by zhenghan008** [comment]
已完成，关闭问题。
